# Generated by Django 2.2.6 on 2019-11-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_file',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store-image/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='store_file',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store-image/%Y/%m/%d'),
        ),
    ]
