# Generated by Django 2.2.6 on 2019-11-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191113_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_file',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='store_file',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
